version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: ../../jenkins/centos  
    
